server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: password-service
          uri: lb://PASSWORD-SERVICE
          predicates:
            - Path=/api/passwords/**

        - id: generator-service
          uri: lb://GENERATOR-SERVICE
          predicates:
            - Path=/api/generator/**

        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/security/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

        # Swagger Docs Routes
        - id: user-service-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        - id: password-service-docs
          uri: lb://PASSWORD-SERVICE
          predicates:
            - Path=/password-service/v3/api-docs/**
          filters:
            - RewritePath=/password-service/(?<segment>.*), /${segment}

        - id: generator-service-docs
          uri: lb://GENERATOR-SERVICE
          predicates:
            - Path=/generator-service/v3/api-docs/**
          filters:
            - RewritePath=/generator-service/(?<segment>.*), /${segment}

        - id: security-service-docs
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security-service/v3/api-docs/**
          filters:
            - RewritePath=/security-service/(?<segment>.*), /${segment}

        - id: notification-service-docs
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/v3/api-docs/**
          filters:
            - RewritePath=/notification-service/(?<segment>.*), /${segment}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: password-service
        url: /password-service/v3/api-docs
      - name: generator-service
        url: /generator-service/v3/api-docs
      - name: security-service
        url: /security-service/v3/api-docs
      - name: notification-service
        url: /notification-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: rev_password_manager_super_secure_jwt_secret_key_2026