server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: password-service
          uri: lb://PASSWORD-SERVICE
          predicates:
            - Path=/api/passwords/**

        - id: user-service-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: password-service-docs
          uri: lb://PASSWORD-SERVICE
          predicates:
            - Path=/password-service/v3/api-docs/**
          filters:
            - RewritePath=/password-service/(?<segment>.*), /$\{segment}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: password-service
        url: /password-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: rev_password_manager_super_secure_jwt_secret_key_2026